config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/favorite', to: 'posts#favorite'
  get '/pv', to: 'posts#pv'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             path: '',
             path_names: {
               sign_up: '',
               sign_in: 'login',
               sign_out: 'logout',
               registration: 'signup'
             },
             controllers: {
               registrations: 'users/registrations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: %i[create destroy]
  end
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: :create
    resource :votes, only: %i[show create]
  end
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: %i[create show]
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  action     :string(255)      default(""), not null
#  checked    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  comment_id :integer
#  post_id    :integer
#  visited_id :integer          not null
#  visitor_id :integer          not null
#  vote_id    :integer
#
# Indexes
#
#  index_notifications_on_comment_id  (comment_id)
#  index_notifications_on_post_id     (post_id)
#  index_notifications_on_visited_id  (visited_id)
#  index_notifications_on_visitor_id  (visitor_id)
#  index_notifications_on_vote_id     (vote_id)
#
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :vote, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @notifications = current_user.passive_notifications.includes(:post, %i[visitor visited]).page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="border border-primary">
  <ul class="list-group">
    <div class="list-group-item">
      <i class="material-icons">face</i>
      <%= link_to visitor.name, user_path(notification.visitor) %>が
    </div>
  </ul>
  <% case notification.action %>
  <% when 'follow' then %>
    <ul class="list-group">
      <div class="list-group-item">
        <i class="material-icons">face</i>
        <%= "あなたをフォローしました" %>
        <i class="material-icons">group_add</i>
      </div>
    </ul>
  <% when 'like' then %>
    <ul class="list-group">
      <div class="list-group-item">
        <i class="material-icons">inbox</i>
        <%= link_to notification.post.title, post_votes_path(notification.post) %>
        <%= "にいいねしました" %>
        <i class="material-icons">favorite</i>
      </div>
    </ul>
  <% when 'comment' then %>
    <ul class="list-group">
      <div class="list-group-item">
        <% if notification.post.user_id == visited.id %>
          <i class="material-icons">inbox</i>
          <%= link_to "あなたの投稿", post_votes_path(notification.post) %>
        <% else %>
          <i class="material-icons">inbox</i>
          <%= link_to post_votes_path(notification.post) do %>
            <%= notification.post.user.name + 'の投稿' %>
          <% end %>
        <% end %>
        <%= "にコメントしました" %>
        <i class="material-icons">sms</i>
      </div>
    </ul>
  <% when 'vote' then %>
    <ul class="list-group">
      <div class="list-group-item">
        <i class="material-icons">inbox</i>
        <%= link_to "あなたの投稿", post_votes_path(notification.post) %>
        <%= "に回答しました" %>
        <i class="material-icons">sms</i>
      </div>
    </ul>
  <% end %>
</div>
<p class="text-right"><%= time_ago_in_words(notification.created_at).upcase %>前</p>

app/views/notifications/index.html.erb
<% provide(:title, '通知') %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Notifications</li>
    </ol>
  </nav>
  <% if @notifications.exists? %>
    <ul class="notification-list jscroll">
      <%= render @notifications %>
      <%= paginate @notifications %>
    </ul>
  <% else %>
    <p class="text-center">まだ通知はありません</p>
  <% end %>
  <%= render "posts/post_btn" %>
</div>