config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/favorite', to: 'posts#favorite'
  get '/pv', to: 'posts#pv'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             path: '',
             path_names: {
               sign_up: '',
               sign_in: 'login',
               sign_out: 'logout',
               registration: 'signup'
             },
             controllers: {
               registrations: 'users/registrations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: %i[create destroy]
  end
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: :create
    resource :votes, only: %i[show create]
  end
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: %i[create show]
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#  user_id    :integer
#
# Indexes
#
#  index_likes_on_post_id              (post_id)
#  index_likes_on_post_id_and_user_id  (post_id,user_id) UNIQUE
#  index_likes_on_user_id              (user_id)
#
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
    @post.create_notification_like!(current_user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(post) %>
    <%= link_to post_likes_path(post), method: :delete, remote: true do %>
      <i class="material-icons favorite-icon">favorite</i>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true do %>
      <i class="material-icons favorite-icon">favorite_border</i>
    <% end %>
  <% end %>
  <%= post.likes.count %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= escape_javascript(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= escape_javascript(render partial: 'likes/like', locals: {post: @post}) %>");