config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/favorite', to: 'posts#favorite'
  get '/pv', to: 'posts#pv'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             path: '',
             path_names: {
               sign_up: '',
               sign_in: 'login',
               sign_out: 'logout',
               registration: 'signup'
             },
             controllers: {
               registrations: 'users/registrations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: %i[create destroy]
  end
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: :create
    resource :votes, only: %i[show create]
  end
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: %i[create show]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin_flg              :boolean
#  avatar                 :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  name                   :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :options, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def like(post)
    likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    likes.find_by(post_id: post.id).destroy
  end

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def already_voted?(post)
    votes.exists?(post_id: post.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      visited_id: id,
      action: 'follow'
    )
    notification.save if notification.valid?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :forbid_guest_user, { only: %i[update destroy] }

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def forbid_guest_user
    return unless @user.email == 'guest@example.com'

    flash[:alert] = 'ゲストユーザーのため変更出来ません。'
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  PER = 10

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(PER)
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(:taggings)
    @following = @user.following
    @followers = @user.followers
    @liked_posts = @user.liked_posts.includes(:taggings, [:user])
    @current_user_entry = Entry.where(user_id: current_user.id)
    return if @user.id == current_user.id

    @current_user_entry.each do |cu|
      @user.entries.each do |u|
        if cu.room_id == u.room_id
          @is_room = true
          @room_id = cu.room_id
        end
      end
    end
    return if @is_room

    @room = Room.new
    @entry = Entry.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form_<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= link_to "フォロー中", user_relationships_path(user), method: :delete, remote: true, class:'btn btn-primary btn-raised btn-block' %>
    <% else %>
      <%= link_to "フォロー", user_relationships_path(user), method: :post, remote: true, class:'btn btn-secondary btn-raised btn-block' %>
    <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class="profile text-center">
  <% if object.avatar.present? %>
    <%= link_to image_tag(object.avatar.thumb.url, :size => '150x150', id: :img_prev, class: "rounded-circle"), object %>
  <% else %>
    <%= link_to image_tag("noimage.jpeg", :size => '150x150', id: :img_prev, class: "rounded-circle"), object %>
  <% end %>
  <p><%= object.name %></p>
</div>

app/views/users/_show_follows.html.erb
<div class="col-md-6 mb-3">
  <div class="card align-items-center pt-3">
    <% if user.avatar.present? %>
      <%= link_to image_tag(user.avatar.thumb.url, :size => '150x150', class: "rounded-circle"), user %>
    <% else %>
      <%= link_to image_tag("nouser.png", :size => '150x150', class: "rounded-circle"), user %>
    <% end %>
    <p class="text-center"><%= user.name %></p>
  </div>
</div>

app/views/users/_user.html.erb
<div class="col-md-6">
  <div class="card pt-3 mb-3">
    <div class="card-title">
      <%= render 'profile', object: user %>
      <%= render 'follow_form', user: user %>
      <% if current_user?(user) %>
        <%= link_to "マイページ", user_path(current_user), class:'btn btn-dark btn-raised btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user_search_form.html.erb
<div class="mb-3">
  <button class="btn bmd-btn-icon" for="search" data-toggle="collapse" data-target="#collapse-search" aria-expanded="false" aria-controls="collapse-search">
    <i class="material-icons">search</i>
  </button>
</div>
<span id="collapse-search" class="collapse">
    <%= search_form_for q, url: url do |f| %>
    <div class="input-group mb-3">
      <%= f.search_field :name_cont, class: "form-control", type:"text", id:"search" %>
      <div class="input-group-append">
        <%= f.submit '検索する', class: "btn btn-info btn-raised" %>
      </div>
    </div>
  <% end %>
</span>

app/views/users/index.html.erb
<% provide(:title, 'ユーザーを探す') %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Users</li>
    </ol>
  </nav>
  <%= render 'user_search_form', url: users_path, q: @q %>
  <ul class="user-list jscroll">
    <div class="row">
      <%= render @users %>
      <%= paginate @users %>
    </div>
  </ul>
  <%= render "posts/post_btn" %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'ユーザー詳細') %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">User</li>
    </ol>
  </nav>
  <div class="user_info">
    <%= render 'profile', object: @user %>
    <%= render 'follow_form', user: @user %>
    <% unless current_user?(@user) %>
      <% if (current_user.following?(@user)) && (@user.following?(current_user))  %>
        <% if @is_room == true %>
          <p class="user-show-room"><a href="/rooms/<%= @room_id %>" class="btn btn-success btn-raised btn-block">チャットへ</a>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class:"btn btn-success btn-raised btn-block user-show-chat"%>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <ul class="nav nav-tabs bg-primary justify-content-center mt-3 mb-3" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="item1-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true">
        投稿<span><%= @posts.count %></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="item2-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="false">
        いいね<span><%= @user.liked_posts.count %></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="item3-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="false">
        フォロー<span><%= @user.following.count %></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="item4-tab" data-toggle="tab" href="#item4" role="tab" aria-controls="item4" aria-selected="false">
        フォロワー<span id="followers"><%= @user.followers.count %></span>
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="item1" role="tabpanel" aria-labelledby="item1-tab">
      <ul class="post-list jscroll">
        <%= render @posts %>
      </ul>
    </div>
    <div class="tab-pane fade" id="item2" role="tabpanel" aria-labelledby="item2-tab">
      <ul class="post-list jscroll">
        <%= render partial: 'posts/post', collection: @liked_posts, as: :post %>
      </ul>
    </div>
    <div class="tab-pane fade" id="item3" role="tabpanel" aria-labelledby="item3-tab">
      <ul class="user-list jscroll">
        <div class="row">
          <%= render partial: 'show_follows', collection: @following, as: :user %>
        </div>
      </ul>
    </div>
    <div class="tab-pane fade" id="item4" role="tabpanel" aria-labelledby="item4-tab">
      <ul class="user-list jscroll">
        <div class="row">
          <%= render partial: 'show_follows', collection: @followers, as: :user %>
        </div>
      </ul>
    </div>
  </div>
  <%= render "posts/post_btn" %>
</div>