config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/favorite', to: 'posts#favorite'
  get '/pv', to: 'posts#pv'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             path: '',
             path_names: {
               sign_up: '',
               sign_in: 'login',
               sign_out: 'logout',
               registration: 'signup'
             },
             controllers: {
               registrations: 'users/registrations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: %i[create destroy]
  end
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: :create
    resource :votes, only: %i[show create]
  end
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: %i[create show]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                :bigint           not null, primary key
#  image             :string(255)
#  impressions_count :integer          default(0)
#  title             :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#
# Indexes
#
#  index_posts_on_user_id                 (user_id)
#  index_posts_on_user_id_and_created_at  (user_id,created_at)
#
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :options, dependent: :destroy, inverse_of: :post
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true
  is_impressionable counter_cache: true
  acts_as_taggable

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: 'like'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  def create_notification_vote!(current_user, vote_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      vote_id: vote_id,
      visited_id: user_id,
      action: 'vote'
    )
    notification.save if notification.valid?
  end

  def comment_count
    Comment.where({ post_id: id }).count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy
  before_action lambda {
    set_post
    already_voted_user
    reject_current_user
  }, only: :show

  def index
    @q = Post.ransack(params[:q])
    @posts = if params[:tag_name]
               Post.includes(:taggings, :user).tagged_with(params[:tag_name].to_s).page(params[:page]).per(10)
             else
               @q.result.includes(:taggings, :user).order('created_at DESC').page(params[:page]).per(10)
             end
  end

  def new
    @post = current_user.posts.build
    num = 0
    while num < 2
      @post.options.build
      num += 1
    end
  end

  def show
    @vote = current_user.votes.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = '投稿が完了しました'
      redirect_to posts_path
    else
      render 'posts/new'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_back(fallback_location: posts_path)
  end

  def favorite
    @posts = Post.includes(:taggings, :user).find(Like.group(:post_id).order(Arel.sql('count(post_id) desc')).limit(5).pluck(:post_id))
  end

  def pv
    @posts = Post.includes(:taggings, :user).order(impressions_count: 'DESC').take(5)
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :tag_list, options_attributes: %i[id title _destroy user_id])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def already_voted_user
    voted = current_user.votes.find_by(post_id: params[:id])
    return if voted.nil?

    redirect_to post_votes_path(@post)
    flash[:warning] = '既に回答しています'
  end

  def reject_current_user
    return unless @post.user == current_user

    redirect_back(fallback_location: posts_path)
    flash[:alert] = '自分で回答は出来ません'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<li class="list-group">
  <div class="list-group-item border border-primary">
    <i class="material-icons">sms</i>
    <%= comment.content %>
    <span class="label label-default label-pill">
      <%= link_to comment.user.name, comment.user %>
      <i class="material-icons">face</i>
    </span>
  </div>
</li>
<p class="text-right"><%= time_ago_in_words(comment.created_at).upcase %>前</p>

app/views/posts/_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title, class:"bmd-label-static" %>
    <%= f.text_field :title, class: 'form-control option_titles', required: true %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= link_to_remove_association f do %>
      <i class="material-icons">clear</i>
    <% end%>
  </div>
</div>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <div class="card mb-3 pt-3">
    <div class="card-body row">
      <div class="col-md-2">
        <div class="card-title text-center">
          <div>
            <% if post.user.avatar? %>
              <%= link_to image_tag(post.user.avatar.thumb.url, :size => '100x100', class: "rounded-circle"), post.user %>
            <% else %>
              <%= link_to image_tag("noimage.jpeg", :size => '100x100', class: "rounded-circle"), post.user %>
            <% end %>
          </div>
          <span><%= link_to post.user.name, post.user %></span>
        </div>
      </div>
      <div class="col-md-10">
        <h2 class="card-subtitle text-center mb-5">
        <% if current_page?(pv_path) || current_page?(favorite_path) %>
          <div class="mb-1 ranking"><%= post_counter + 1 %>位</div>
        <% end %>
          <%= post.title %>
            <div class="tag_button">
              <% post.tag_list.each do |tag| %>
                <%= link_to tag, posts_path(tag_name: tag), class: "badge badge-secondary tags" %>
              <% end %>
            </div>
        </h2>
        <div class="card-text">
          <div class="row justify-content-between ml-3 mr-3">
            <div class="impression_count">
              <i class="material-icons impression-icon">remove_red_eye</i>
              <%= post.impressionist_count(:filter=>:session_hash) %>
            </div>
            <div class="comment_count">
              <span class="material-icons comment-icon">comment</span>
              <%= post.comment_count %>
            </div>
            <% if current_user?(post.user) %>
              <span>
                <i class="material-icons favorite-icon">favorite</i>
                <%= post.likes.count %>
              </span>
              <div class="delete_button">
                <%= link_to post, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
                  <i class="material-icons delete-icon">delete_forever</i>
                <% end %>
              </div>
            <% else %>
              <div id="likes_buttons_<%= post.id %>">
                <%= render partial: 'likes/like', locals: { post: post} %>
              </div>
            <% end %>
          </div>
          <div class="poll_btn mt-3">
            <% if current_user?(post.user) || current_user.already_voted?(post) %>
              <div class="result">
                <%= link_to post_votes_path(post), class:"btn btn-primary btn-raised btn-block" do %>
                  結果を見る<i class="material-icons">equalizer</i>
                <% end %>
              </div>
            <% else %>
              <div class="answer">
                <%= link_to post_path(post), class:"btn btn-secondary btn-raised btn-block" do %>
                  回答する<i class="material-icons">check</i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/posts/_post_btn.html.erb
<% if user_signed_in? %>
  <%= link_to new_post_path, class:"new-post-link" do %>
    <i class="material-icons new-post-btn">add_circle</i>
  <% end %>
<% end %>

app/views/posts/_post_search_form.html.erb
<div class="mb-3 mt-3">
  <button class="btn bmd-btn-icon" for="search" data-toggle="collapse" data-target="#collapse-search" aria-expanded="false" aria-controls="collapse-search">
    <i class="material-icons">search</i>
  </button>
</div>
<span id="collapse-search" class="collapse">
    <%= search_form_for q, url: url do |f| %>
    <div class="input-group mb-3">
      <%= f.search_field :title_or_tags_name_cont, class: "form-control", type:"text", id:"search" %>
      <div class="input-group-append">
        <%= f.submit '検索する', class: "btn btn-info btn-raised" %>
      </div>
    </div>
  <% end %>
</span>

app/views/posts/favorite.html.erb
<% provide(:title, 'いいねランキング') %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Favorite</li>
    </ol>
  </nav>
  <ul class="post-list">
    <%= render @posts %>
  </ul>
  <%= render "post_btn" %>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'アンケートを探す') %>
<div class="container-fluid">
  <%= render 'post_search_form', url: posts_path, q: @q %>
  <ul class="post-list jscroll">
    <%= render @posts %>
    <%= paginate @posts %>
  </ul>
  <%= render "posts/post_btn" %>
</div>

app/views/posts/new.html.erb
<% provide(:title, '新規投稿') %>
<div class="container-fluid">
  <div class="new-page">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">NewPost</li>
    </ol>
  </nav>
  <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :title, class:"bmd-label-static" %>
      <%= f.text_field :title, class: 'form-control', required: true %>
      <span class="bmd-help">30文字以内で入力してください</span>
    </div>
    <div id="options">
      <%= f.fields_for :options do |option| %>
        <%= render 'option_fields', f: option %>
      <% end %>
      <div class="links">
        <%= link_to_add_association f, :options do %>
          <i class="material-icons">add_box</i>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :tag_list, class:"bmd-label-static" %>
      <%= f.text_field :tag_list, value: @post.tag_list.join(','), data: {role: "tagsinput"} %>
    </div>
    <div class="form-group">
      <%= f.label :image, class:"bmd-label-static" %>
      <label class="form-control">
      <% if @post.image.present? %>
        <%= image_tag @post.image_url, id: :img_prev, :size => '400x400', class: "form-control" %>
      <% else %>
        <%= image_tag "noimage.jpeg", id: :img_prev, :size => '400x400', class: "form-control"  %>
      <% end %>
      <br>
        <span class="btn btn-raised btn-secondary btn-block">画像ファイルを追加する</span>
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id: :post_img, class: "d-none" %>
      </label>
    </div>
    <%= f.submit "投稿", class: "btn btn-primary btn-raised btn-block" %>
  <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    function check_to_hide_or_show_add_link() {
      if ($('#options .nested-fields:visible').length == 5) {
        $('#options .links a').hide();
      } else {
        $('#options .links a').show();
      }
    }
    $('#options').on('cocoon:after-insert', function() {
      check_to_hide_or_show_add_link();
    });
    $('#options').on('cocoon:after-remove', function() {
      check_to_hide_or_show_add_link();
    });
      check_to_hide_or_show_add_link();
  });
</script>

<script type="text/javascript">
  $(function() {
    function check_to_hide_or_show_delete_link() {
      if ($('#options .nested-fields:visible').length <= 2) {
        $('#options .nested-fields a').hide();
      } else {
        $('#options .nested-fields a').show();
      }
    }
    $('#options').on('cocoon:before-insert', function() {
      check_to_hide_or_show_delete_link();
    });
    $('#options').on('cocoon:after-insert', function() {
      check_to_hide_or_show_delete_link();
    });
    $('#options').on('cocoon:after-remove', function() {
      check_to_hide_or_show_delete_link();
    });
      check_to_hide_or_show_delete_link();
  });
</script>

<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#post_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/posts/pv.html.erb
<% provide(:title, 'PVランキング') %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/posts">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">PV</li>
    </ol>
  </nav>
  <ul class="post-list">
    <%= render @posts %>
  </ul>
  <%= render "post_btn" %>
</div>

app/views/posts/show.html.erb
<% provide(:title, '投稿詳細') %>
<div class="container-fluid">
  <div class="new-page">
    <div class="text-center">
      <h1 class="mt-5"><%= @post.title %></h1>
      <% if @post.image.present? %>
        <%= image_tag @post.image.url %>
      <% end %>
      <%= form_for [@post, @vote] do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <% @post.options.each do |option| %>
          <div class="form-group">
            <div class="radio radio-primary">
              <label>
                <%= radio_button("vote", "option_id", option.id) %>
                <%= option.title %>
              </label>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.submit "回答", class: "btn btn-primary btn-raised btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>